{
    "openapi": "3.0.0",
    "info": {
        "title": "Atlas",
        "description": "Essa é uma documentação sobre a Atlas API",
        "version": "1.0.0",
        "contact": {
            "email": "felype99azevedo@gmail.com"
        }
    },
    "components": {
        "securitySchemes": {
            "ApiKeyAuth": {
                "type": "apiKey",
                "in": "header",
                "name": "user_id"
            }
        }
    },
    "paths": {
        "/users": {
            "post": {
                "tags": [
                    "Users"
                ],
                "summary": "Cria um novo usuário",
                "description": "Cria um novo usuário",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "name": {
                                        "type": "string"
                                    },
                                    "email": {
                                        "type": "string"
                                    }
                                },
                                "example": {
                                    "name": "Rocketseat",
                                    "email": "oi@rocketseat.com.br"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Operação realizada com sucesso",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "admin": {
                                            "type": "boolean"
                                        },
                                        "id": {
                                            "type": "string"
                                        },
                                        "name": {
                                            "type": "string"
                                        },
                                        "email": {
                                            "type": "string"
                                        },
                                        "created_at": {
                                            "type": "string"
                                        },
                                        "updated_at": {
                                            "type": "string"
                                        }
                                    },
                                    "example": {
                                        "id": "1a9ef8d2-efd4-45e5-94dd-861f9f2dbf28",
                                        "admin": false,
                                        "name": "Rocketseat",
                                        "email": "oi@rocketseat.com.br",
                                        "created_at": "2022-09-02T00:36:38.393Z",
                                        "updated_at": "2022-09-02T00:36:38.393Z"
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Email já está sendo utilizado",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {
                                        "error": "User already exists!"
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "get": {
                "tags": [
                    "Users"
                ],
                "summary": "Retorna todos os usuários",
                "description": "Somente usuário `admin` pode retornar",
                "parameters": [
                    {
                        "in": "header",
                        "name": "user_id",
                        "schema": {
                            "type": "string",
                            "format": "uuid",
                            "required": true
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Operação realizada com sucesso",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "properties": {
                                        "admin": {
                                            "type": "boolean"
                                        },
                                        "id": {
                                            "type": "string"
                                        },
                                        "name": {
                                            "type": "string"
                                        },
                                        "email": {
                                            "type": "string"
                                        },
                                        "created_at": {
                                            "type": "string"
                                        },
                                        "updated_at": {
                                            "type": "string"
                                        }
                                    },
                                    "example": [
                                        {
                                            "id": "1a9ef8d2-efd4-45e5-94dd-861f9f2dbf28",
                                            "admin": false,
                                            "name": "Rocketseat",
                                            "email": "oi@rocketseat.com.br",
                                            "created_at": "2022-09-02T00:36:38.393Z",
                                            "updated_at": "2022-09-02T00:36:38.393Z"
                                        },
                                        {
                                            "id": "1abef8d2-efd4-41t5-94dd-861g9f2dbf27",
                                            "admin": false,
                                            "name": "Vinicius Fraga",
                                            "email": "vinicius.fraga@rocketseat.com.br",
                                            "created_at": "2022-09-02T00:36:38.393Z",
                                            "updated_at": "2022-09-02T00:36:38.393Z"
                                        }
                                    ]
                                }
                            }
                        }
                    }
                }
            }
        },
        "/users/{user_id}": {
            "get": {
                "tags": [
                    "Users"
                ],
                "summary": "Retorna um usuário específico.",
                "parameters": [
                    {
                        "in": "path",
                        "name": "user_id",
                        "description": "ID do usuário",
                        "required": true,
                        "schema": {
                            "example": "user_id - ID do usuário"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Operação realizada com sucesso",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "admin": {
                                            "type": "boolean"
                                        },
                                        "id": {
                                            "type": "string"
                                        },
                                        "name": {
                                            "type": "string"
                                        },
                                        "email": {
                                            "type": "string"
                                        },
                                        "created_at": {
                                            "type": "string"
                                        },
                                        "updated_at": {
                                            "type": "string"
                                        }
                                    },
                                    "example": {
                                        "id": "1a9ef8d2-efd4-45e5-94dd-861f9f2dbf28",
                                        "admin": false,
                                        "name": "Rocketseat",
                                        "email": "oi@rocketseat.com.br",
                                        "created_at": "2022-09-02T00:36:38.393Z",
                                        "updated_at": "2022-09-02T00:36:38.393Z"
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Usuário não encontrado",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {
                                        "error": "User not found."
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },

        "/users/{user_id}/admin": {
            "patch": {
                "tags": [
                    "Users"
                ],
                "summary": "Torna admin um usuário",
                "parameters": [
                    {
                        "in": "path",
                        "name": "user_id",
                        "required": true,
                        "schema": {
                            "type": "string($uuid)"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Operação realizada com sucesso",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "admin": {
                                            "type": "boolean"
                                        },
                                        "id": {
                                            "type": "string"
                                        },
                                        "name": {
                                            "type": "string"
                                        },
                                        "email": {
                                            "type": "string"
                                        },
                                        "created_at": {
                                            "type": "string"
                                        },
                                        "updated_at": {
                                            "type": "string"
                                        }
                                    },
                                    "example": {
                                        "id": "1a9ef8d2-efd4-45e5-94dd-861f9f2dbf28",
                                        "admin": true,
                                        "name": "Rocketseat",
                                        "email": "oi@rocketseat.com.br",
                                        "created_at": "2022-09-02T00:36:38.393Z",
                                        "updated_at": "2022-09-02T00:36:38.393Z"
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Usuário não encontrado",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {
                                        "error": "User not found."
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}